#!groovy

pipeline {

  agent any

  environment {
    GIT_URL = "https://github.com/jenkinsfiles-tm/ansible-configs_aws.git"
  }

  parameters {
    string(
      name: 'GIT_BRANCHES',
      defaultValue: '',
      description: "Git branch or tag name or commit id of GIT_URL of Jenkins job configuration file"
    )
  }

  stages {
    stage('Ansible CI') {
      failFast false
      parallel {
        stage('Install ansible') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "ansible/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_ansible"
                            )
                          ]
          }
        }

        stage('Install AWS CLI') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "awscli/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_awscli"
                            )
                          ]
          }
        }

        stage('Install AWX') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "awx/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_awx"
                            )
                          ]
          }
        }

        stage('Install chrome') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "chrome/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_chrome"
                            )
                          ]
          }
        }

        stage('Install docker') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "docker/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_docker"
                            )
                          ]
          }
        }

        stage('Install exa') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "exa/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_exa"
                            )
                          ]
          }
        }

        stage('Install Jenkins') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "jenkins_install/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_jenkins_install"
                            )
                          ]
          }
        }

        stage('Install PlantUML Server') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "plantuml_server/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_plantuml_server"
                            )
                          ]
          }
        }

        stage('Install VNC Server') {
          steps {
            build job: 'ansible/playbook',
              parameters: [
                            string(
                              name: 'CONFIG_FILE_PATH',
                              value: "vnc_server/config.yml"
                            ),
                            string(
                              name: 'GIT_BRANCHES',
                              value: "${params.GIT_BRANCHES}"
                            ),
                            string(
                              name: 'GIT_URL',
                              value: "${env.GIT_URL}"
                            ),
                            string(
                              name: 'WORKING_DIR',
                              value: "jeknins_job_ansible_cli_vnc_server"
                            )
                          ]
          }
        }
      }
    }
  }
}
